# Site settings
title: Random Technicalities
email: occ@occ.me
description: >-
  A blog on random thoughts and experiments
baseurl: "/"
url: "https://occ.me"
twitter_username: onur_cakmak
github_username:  occ
linkedin_username: onurcakmak

google_analytics: UA-116294962-1
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
