baseURL: https://occ.me/
languageCode: en-us
title: Random Technicalities
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "Hi 👋"

  socialIcons:
    - name: github
      url: https://github.com/occ
    - name: linkedin
      url: https://www.linkedin.com/in/onurcakmak/
    - name: mastodon
      url: https://m.occ.me/@occ

googleAnalytics: G-EDXTWJ9TLQ
